USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE RESOURCE MONITOR rm_data_engg_quota
WITH CREDIT_QUOTA = 40
FREQUENCY = DAILY
START_TIMESTAMP = TO_TIMESTAMP('2026-09-01 00:00:00')
TRIGGERS ON 50 PERCENT DO NOTIFY
         ON 75 PERCENT DO NOTIFY
         ON 95 PERCENT DO SUSPEND   -- Wait for running queries to finish
         ON 100 PERCENT DO SUSPEND_IMMEDIATE;