USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE RESOURCE MONITOR rm_data_engg_quota
WITH CREDIT_QUOTA = 40
FREQUENCY = DAILY
START_TIMESTAMP = IMMEDIATELY
TRIGGERS ON 50 PERCENT DO NOTIFY
         ON 75 PERCENT DO NOTIFY
         ON 95 PERCENT DO SUSPEND   -- Wait for running queries to finish
         ON 100 PERCENT DO SUSPEND_IMMEDIATE;

SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.RESOURCE_MONITORS;